import numpy as np
import torch
from scipy.io import loadmat
import matplotlib.pyplot as plt
import pandas as pd
import json
import os
from models import (interpolation, SRCNN_train, SRCNN_predict, 
                    DNCNN_train, DNCNN_predict)

# https://github.com/Mehran-Soltani/ChannelNet/blob/master/ChannelNet_train.py

EPOCHS = 300  # Set to 2 for testing, increase to 200-300 for actual training


def add_awgn_noise(perfect_channel, snr_db):
    """
    Add AWGN (Additive White Gaussian Noise) to perfect channel
    
    Args:
        perfect_channel: Perfect channel matrix (complex values)
        snr_db: Signal-to-Noise Ratio in dB
    
    Returns:
        noisy_channel: Channel with AWGN noise added
    """
    # Convert SNR from dB to linear scale
    snr_linear = 10 ** (snr_db / 10.0)
    
    # Calculate signal power
    signal_power = np.mean(np.abs(perfect_channel) ** 2)
    
    # Calculate noise power based on desired SNR
    noise_power = signal_power / snr_linear
    
    # Generate complex AWGN noise
    # Real and imaginary parts are independent Gaussian
    noise_real = np.sqrt(noise_power / 2) * np.random.randn(*perfect_channel.shape)
    noise_imag = np.sqrt(noise_power / 2) * np.random.randn(*perfect_channel.shape)
    noise = noise_real + 1j * noise_imag
    
    # Add noise to signal
    noisy_channel = perfect_channel + noise
    
    # Verify SNR (optional, for debugging)
    actual_signal_power = np.mean(np.abs(perfect_channel) ** 2)
    actual_noise_power = np.mean(np.abs(noise) ** 2)
    actual_snr_db = 10 * np.log10(actual_signal_power / actual_noise_power)
    
    # print(f"  Target SNR: {snr_db:.2f} dB, Actual SNR: {actual_snr_db:.2f} dB")
    
    return noisy_channel

def load_data_for_snr(snr, perfect, Number_of_pilots, generate_noise=True):
    """
    Load and prepare data for a specific SNR value
    
    Args:
        snr: SNR value in dB
        perfect: Perfect channel data (complex array)
        Number_of_pilots: Number of pilots
        generate_noise: If True, generate AWGN noise. If False, load from file.
    
    Returns:
        interp_noisy: Interpolated noisy data
        perfect_image: Perfect channel data
    """
    print(f"  Loading data for SNR = {snr} dB...")
    
    if generate_noise:
        # Generate noisy channel by adding AWGN to perfect channel
        print(f"    Generating AWGN noise for SNR={snr} dB...")
        noisy_input = add_awgn_noise(perfect, snr)
    else:
        # Load noisy data from file (for training data)
        try:
            noisy_input = loadmat(f"My_noisy_H_{snr}.mat")["My_noisy_H"]
            print(f"    Loaded noisy data from file")
        except:
            try:
                noisy_input = loadmat(f"Noisy_VehA_SNR_{snr}.mat")[f"VehA_noisy_{snr}"]
                print(f"    Loaded noisy data from file")
            except:
                print(f"  ⚠ Warning: Could not load noisy data for SNR={snr}")
                return None, None
    
    # Interpolate noisy channel estimates
    interp_noisy = interpolation(noisy_input, snr, Number_of_pilots, 'rbf')
    
    # Prepare perfect channel estimates (same for all SNRs)
    perfect_image = np.zeros((len(perfect), 72, 14, 2))
    perfect_image[:, :, :, 0] = np.real(perfect)
    perfect_image[:, :, :, 1] = np.imag(perfect)
    perfect_image = np.concatenate((perfect_image[:, :, :, 0], perfect_image[:, :, :, 1]), 
                                   axis=0).reshape(2*len(perfect), 72, 14, 1)
    
    return interp_noisy, perfect_image


def test_on_multiple_snrs(model_type, channel_model, Number_of_pilots, train_snr, 
                          test_snr_list, perfect, idx_random, device='cuda'):
    """
    Test a trained model on multiple SNR values by generating AWGN noise
    
    Args:
        model_type: 'SRCNN' or 'DNCNN'
        channel_model: Channel model name
        Number_of_pilots: Number of pilots
        train_snr: SNR used for training
        test_snr_list: List of SNR values to test on
        perfect: Perfect channel data (complex array)
        idx_random: Indices for train/val split
        device: Device to run on
    
    Returns:
        results_dict: Dictionary containing MSE for each test SNR
    """
    
    print("\n" + "="*70)
    print(f"Testing {model_type} (trained on SNR={train_snr}) on Multiple SNRs")
    print("="*70)
    print("Note: Test data generated by adding AWGN noise to perfect channel")
    
    results = {
        'model_type': model_type,
        'train_snr': train_snr,
        'test_results': {}
    }
    
    for test_snr in test_snr_list:
        print(f"\n{'='*70}")
        print(f"Testing on SNR = {test_snr} dB")
        print(f"{'='*70}")
        
        # Generate test data with AWGN noise at this SNR
        interp_noisy, perfect_image = load_data_for_snr(test_snr, perfect, Number_of_pilots, 
                                                        generate_noise=True)
        
        if interp_noisy is None:
            print(f"  Skipping SNR={test_snr} (data generation failed)")
            continue
        
        # Use same validation split as training
        test_data = interp_noisy[~idx_random, :, :, :]
        test_label = perfect_image[~idx_random, :, :, :]
        
        print(f"  Test samples: {len(test_data)}")
        
        # Predict using model trained on train_snr
        try:
            if model_type == 'SRCNN':
                predictions = SRCNN_predict(test_data, channel_model, Number_of_pilots, 
                                           train_snr, batch_size=128, device=device)
            else:  # DNCNN
                predictions = DNCNN_predict(test_data, channel_model, Number_of_pilots,
                                           train_snr, batch_size=128, device=device)
            
            # Calculate MSE
            mse = np.mean((predictions - test_label) ** 2)
            
            # Store results
            results['test_results'][test_snr] = {
                'mse': float(mse),
                'num_samples': len(test_data)
            }
            
            # Print results
            status = "✓ (Train SNR)" if test_snr == train_snr else "⚠ (Different SNR)"
            print(f"  MSE: {mse:.6f} {status}")
            
        except Exception as e:
            print(f"  Error predicting on SNR={test_snr}: {e}")
            results['test_results'][test_snr] = {
                'mse': None,
                'error': str(e)
            }
    
    return results


def save_results(results_dict, output_dir='results'):
    """
    Save test results in multiple formats
    
    Args:
        results_dict: Dictionary containing test results
        output_dir: Directory to save results
    """
    
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Extract data for saving
    model_type = results_dict['model_type']
    train_snr = results_dict['train_snr']
    test_results = results_dict['test_results']
    
    # 1. Save as JSON
    json_file = os.path.join(output_dir, f'{model_type}_train{train_snr}_results.json')
    with open(json_file, 'w') as f:
        json.dump(results_dict, f, indent=4)
    print(f"  ✓ Saved JSON results to: {json_file}")
    
    # 2. Save as CSV
    csv_data = []
    for test_snr, result in test_results.items():
        if 'mse' in result and result['mse'] is not None:
            csv_data.append({
                'Test_SNR_dB': test_snr,
                'MSE': result['mse'],
                'Num_Samples': result.get('num_samples', 'N/A')
            })
    
    if csv_data:
        df = pd.DataFrame(csv_data)
        df = df.sort_values('Test_SNR_dB')  # Sort by SNR
        csv_file = os.path.join(output_dir, f'{model_type}_train{train_snr}_results.csv')
        df.to_csv(csv_file, index=False)
        print(f"  ✓ Saved CSV results to: {csv_file}")
    
    # 3. Save as text file (human-readable)
    txt_file = os.path.join(output_dir, f'{model_type}_train{train_snr}_results.txt')
    with open(txt_file, 'w') as f:
        f.write(f"{'='*70}\n")
        f.write(f"{model_type} Model - Cross-SNR Performance\n")
        f.write(f"{'='*70}\n")
        f.write(f"Training SNR: {train_snr} dB\n")
        f.write(f"{'='*70}\n\n")
        
        f.write(f"{'Test SNR (dB)':<20} {'MSE':<20} {'Status'}\n")
        f.write(f"{'-'*70}\n")
        
        for test_snr in sorted(test_results.keys()):
            result = test_results[test_snr]
            if 'mse' in result and result['mse'] is not None:
                mse = result['mse']
                status = "✓ Train SNR" if test_snr == train_snr else "⚠ Cross-SNR"
                f.write(f"{test_snr:<20} {mse:<20.6f} {status}\n")
        
        f.write(f"\n{'='*70}\n")
        f.write("Notes:\n")
        f.write("  ✓ = Model tested on same SNR as training (expected best performance)\n")
        f.write("  ⚠ = Model tested on different SNR (performance may degrade)\n")
    
    print(f"  ✓ Saved text results to: {txt_file}")


def plot_cross_snr_results(srcnn_results, dncnn_results, output_dir='results'):
    """
    Plot MSE vs SNR for both models
    
    Args:
        srcnn_results: SRCNN test results
        dncnn_results: DNCNN test results
        output_dir: Directory to save plot
    """
    
    train_snr = srcnn_results['train_snr']
    
    # Extract data
    srcnn_snrs = []
    srcnn_mses = []
    for snr, result in sorted(srcnn_results['test_results'].items()):
        if 'mse' in result and result['mse'] is not None:
            srcnn_snrs.append(snr)
            srcnn_mses.append(result['mse'])
    
    dncnn_snrs = []
    dncnn_mses = []
    for snr, result in sorted(dncnn_results['test_results'].items()):
        if 'mse' in result and result['mse'] is not None:
            dncnn_snrs.append(snr)
            dncnn_mses.append(result['mse'])
    
    # Create plot
    plt.figure(figsize=(12, 8))
    
    # Plot SRCNN
    plt.subplot(2, 1, 1)
    plt.plot(srcnn_snrs, srcnn_mses, 'o-', linewidth=2, markersize=10, label='SRCNN')
    plt.axvline(x=train_snr, color='r', linestyle='--', alpha=0.7, label=f'Training SNR = {train_snr} dB')
    plt.xlabel('Test SNR (dB)', fontsize=12)
    plt.ylabel('MSE', fontsize=12)
    plt.title(f'SRCNN: Cross-SNR Performance (Trained on SNR={train_snr} dB)', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=10)
    
    # Annotate points
    for snr, mse in zip(srcnn_snrs, srcnn_mses):
        if snr == train_snr:
            plt.annotate(f'{mse:.4f}★', xy=(snr, mse), xytext=(0, 10),
                        textcoords='offset points', ha='center', fontsize=9, fontweight='bold', color='red')
        else:
            plt.annotate(f'{mse:.4f}', xy=(snr, mse), xytext=(0, 10),
                        textcoords='offset points', ha='center', fontsize=9)
    
    # Plot DNCNN
    plt.subplot(2, 1, 2)
    plt.plot(dncnn_snrs, dncnn_mses, 's-', linewidth=2, markersize=10, label='DNCNN', color='orange')
    plt.axvline(x=train_snr, color='r', linestyle='--', alpha=0.7, label=f'Training SNR = {train_snr} dB')
    plt.xlabel('Test SNR (dB)', fontsize=12)
    plt.ylabel('MSE', fontsize=12)
    plt.title(f'DNCNN: Cross-SNR Performance (Trained on SNR={train_snr} dB)', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=10)
    
    # Annotate points
    for snr, mse in zip(dncnn_snrs, dncnn_mses):
        if snr == train_snr:
            plt.annotate(f'{mse:.4f}★', xy=(snr, mse), xytext=(0, 10),
                        textcoords='offset points', ha='center', fontsize=9, fontweight='bold', color='red')
        else:
            plt.annotate(f'{mse:.4f}', xy=(snr, mse), xytext=(0, 10),
                        textcoords='offset points', ha='center', fontsize=9)
    
    plt.tight_layout()
    
    # Save plot
    os.makedirs(output_dir, exist_ok=True)
    plot_file = os.path.join(output_dir, f'cross_snr_performance_train{train_snr}.png')
    plt.savefig(plot_file, dpi=150, bbox_inches='tight')
    print(f"  ✓ Saved performance plot to: {plot_file}")
    plt.close()


def main():
    # Set device
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Using device: {device}")
    
    # Configuration
    channel_model = "VehA"
    train_snr = 22  # SNR to train on
    Number_of_pilots = 48
    
    # Define SNR values to test on (INCLUDE train_snr in this list)
    test_snr_list = [8, 10, 12, 14, 16, 18, 20]
    
    # Choose data source for training
    # True: Generate AWGN noise, False: Load from file
    use_awgn_for_training = True
    
    print("\n" + "="*70)
    print("MULTI-SNR TESTING CONFIGURATION")
    print("="*70)
    print(f"Training SNR: {train_snr} dB")
    print(f"Test SNR values: {test_snr_list}")
    print(f"Number of pilots: {Number_of_pilots}")
    print(f"Epochs: {EPOCHS}")
    print(f"Training data source: {'AWGN Generated' if use_awgn_for_training else 'From File'}")
    print(f"Test data source: AWGN Generated (always)")
    print("="*70)
    
    # Load perfect channel (same for all SNRs)
    print("\nLoading perfect channel data...")
    perfect = loadmat("Perfect_H_40000.mat")['My_perfect_H']
    print(f"  Perfect channel shape: {perfect.shape}")
    
    # Set random seed for reproducibility of noise generation
    np.random.seed(42)
    
    # Load training data
    print(f"\nLoading training data (SNR={train_snr} dB)...")
    train_interp_noisy, perfect_image = load_data_for_snr(train_snr, perfect, Number_of_pilots, 
                                                          generate_noise=use_awgn_for_training)
    
    if train_interp_noisy is None:
        print(f"ERROR: Could not load training data for SNR={train_snr}")
        return
    
    print(f"  Training data shape: {train_interp_noisy.shape}")
    
    # Split data into training and validation sets
    print("\nSplitting data into train/validation sets...")
    idx_random = np.random.rand(len(perfect_image)) < 0.8  # 80% for training, 20% for validation
    train_data = train_interp_noisy[idx_random, :, :, :]
    train_label = perfect_image[idx_random, :, :, :]
    val_data = train_interp_noisy[~idx_random, :, :, :]
    val_label = perfect_image[~idx_random, :, :, :]
    
    print(f"  Training samples: {len(train_data)}")
    print(f"  Validation samples: {len(val_data)}")
    
    # ========================================================================
    # TRAIN SRCNN
    # ========================================================================
    print("\n" + "="*70)
    print(f"Training SRCNN Model on SNR={train_snr} dB")
    print("="*70)
    SRCNN_train(train_data, train_label, val_data, val_label, 
                channel_model, Number_of_pilots, train_snr, epochs=EPOCHS, device=device)
    
    # Test SRCNN on multiple SNRs (using AWGN generated test data)
    srcnn_results = test_on_multiple_snrs('SRCNN', channel_model, Number_of_pilots, 
                                          train_snr, test_snr_list, perfect, 
                                          idx_random, device)
    
    # ========================================================================
    # TRAIN DNCNN
    # ========================================================================
    print("\n" + "="*70)
    print(f"Training DNCNN Model on SNR={train_snr} dB")
    print("="*70)
    DNCNN_train(train_data, train_label, val_data, val_label, 
                channel_model, Number_of_pilots, train_snr, epochs=EPOCHS, device=device)
    
    # Test DNCNN on multiple SNRs (using AWGN generated test data)
    dncnn_results = test_on_multiple_snrs('DNCNN', channel_model, Number_of_pilots,
                                          train_snr, test_snr_list, perfect,
                                          idx_random, device)
    
    # ========================================================================
    # SAVE RESULTS
    # ========================================================================
    print("\n" + "="*70)
    print("Saving Results")
    print("="*70)
    
    # Save SRCNN results
    print("\nSaving SRCNN results...")
    save_results(srcnn_results, output_dir='results')
    
    # Save DNCNN results
    print("\nSaving DNCNN results...")
    save_results(dncnn_results, output_dir='results')
    
    # Plot comparison
    print("\nCreating performance plots...")
    plot_cross_snr_results(srcnn_results, dncnn_results, output_dir='results')
    
    # ========================================================================
    # PRINT SUMMARY
    # ========================================================================
    print("\n" + "="*70)
    print("SUMMARY OF RESULTS")
    print("="*70)
    
    print(f"\nSRCNN (Trained on SNR={train_snr} dB):")
    print(f"{'Test SNR (dB)':<20} {'MSE':<20} {'Performance'}")
    print("-" * 70)
    for test_snr in sorted(srcnn_results['test_results'].keys()):
        result = srcnn_results['test_results'][test_snr]
        if 'mse' in result and result['mse'] is not None:
            mse = result['mse']
            if mse < 0.001:
                perf = "Excellent ★★★★★"
            elif mse < 0.003:
                perf = "Good ★★★★"
            elif mse < 0.005:
                perf = "Fair ★★★"
            else:
                perf = "Poor ★★"
            
            marker = " ← Train SNR" if test_snr == train_snr else ""
            print(f"{test_snr:<20} {mse:<20.6f} {perf}{marker}")
    
    print(f"\nDNCNN (Trained on SNR={train_snr} dB):")
    print(f"{'Test SNR (dB)':<20} {'MSE':<20} {'Performance'}")
    print("-" * 70)
    for test_snr in sorted(dncnn_results['test_results'].keys()):
        result = dncnn_results['test_results'][test_snr]
        if 'mse' in result and result['mse'] is not None:
            mse = result['mse']
            if mse < 0.001:
                perf = "Excellent ★★★★★"
            elif mse < 0.003:
                perf = "Good ★★★★"
            elif mse < 0.005:
                perf = "Fair ★★★"
            else:
                perf = "Poor ★★"
            
            marker = " ← Train SNR" if test_snr == train_snr else ""
            print(f"{test_snr:<20} {mse:<20.6f} {perf}{marker}")
    
    print("\n" + "="*70)
    print("Training and multi-SNR testing completed!")
    print("="*70)
    print("\nResults saved in 'results/' directory:")
    print("  • JSON files (machine-readable)")
    print("  • CSV files (spreadsheet-compatible)")  
    print("  • TXT files (human-readable)")
    print("  • PNG plots (visualization)")
    print("\nConfiguration options:")
    print(f"  - train_snr = {train_snr}  (SNR to train on)")
    print(f"  - test_snr_list = {test_snr_list}  (SNRs to test on)")
    print(f"  - EPOCHS = {EPOCHS}  (number of training epochs)")
    print(f"  - use_awgn_for_training = {use_awgn_for_training}  (generate AWGN vs load from file)")
    print("\nNote: Test data always uses AWGN noise generated from perfect channel")


if __name__ == "__main__":
    main()